backend:
  name: github
  repo: suncoast-devs/web
publish_mode: editorial_workflow
display_url: https://suncoast.io
media_folder: static/media
public_folder: /media
collections:
  - name: organizations
    label: Organizations
    folder: data/organizations
    create: true
    fields:
      - name: title
        label: Organization Name
        required: true
      - name: "url"
        label: "URL"
        required: true
      - name: "thumbnail"
        label: "Thumbnail Image / Logo"
        widget: "image"
      - name: "founded_on"
        label: "Foundation Date"
        widget: date
